### ISSUE TITLE
Provide the S3 buckets to JPL Dev Team for stage-in

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/maap-hec-aws#64]
## Describe the work to be done.
Enable the MAAP-AWS-HEC account **Read-Only** access to the MAAP Ops buckets for data egress.
Buckets:
- s3://maap-ops-workspace
- s3://nasa-maap-data-store/file-staging ( Note: only GEDI and ICESat2 data are not public )
 
## Definition of Done:
- [x] AWS CLI s3 read from MAAP-AWS-HEC to MAAP-Ops buckets work (private data, not public data)
    - [x]  maap-ops-workspace
    - [x] nasa-maap-data-store
- [x] Documentation provided including Demo code.
- [x] Github repo commits provided

**Comment by jjfrench** [comment]
Simple read bucket policy~
```
Version: "2012-10-17"
Statement:
  - Sid: "Read-only access"
    Effect: Allow
    Principal:
      AWS:
        - "arn:aws:iam:{account_id}:root"
    Action:
      - s3:GetObject
      - s3:ListBucket
      # - s3:GetObjectTagging
      # - s3:GetObjectVersion
      # - s3:GetBucketLocation
    Resource:
      - "arn:aws:s3:::{bucket_name}"
      - "arn:aws:s3:::{bucket_name}/*"
```
